### ISSUE TITLE
Duplicated stations bug fix

### ISSUE THREAD

**Issue by avastar** [DeadAirRT/DeadAirGateOverhaul#1]
cluster_* macros need class="sector" and the optional quota sector="#":
```
<quotas>
        <quota galaxy="1" sector="1" />
</quotas>
<location class="sector" macro="cluster_DA3SCA1_sector001_macro" matchextension="false"/>
```

zone* macros need class="zone" and the optional quota zone="#":
```
<quotas>
        <quota galaxy="1" zone="1" />
</quotas>
<location class="zone" macro="ZoneDAGO7_Cluster_DA2SCA2_Sector001_macro" matchextension="false"/>
```

**Comment by DeadAirRT** [comment]
So I just now saw this but I can't find any that are mismatched. Do you have an example of a wrong one?

**Comment by DeadAirRT** [comment]
Also, the bug is due to ego dlc and god. Not my mod. God should never have been run more than once.

**Comment by avastar** [comment]
I'm thoroughly confused. I distinctly remember a duplication bug of your mod's Scaleplate's stations and me changing a god file as I indicated above, which then removed the duplication bug. At the same time it was experiencing a bug where Avarice and Desecrate Skies were overlapping each other. However, I can no-longer find the original file that I changed. Sorry!

**Comment by DeadAirRT** [comment]
I'm assuming that whatever potentially caused it was cleared up in all the patches. If you ever experience it again, let me know.
